# tests/test_scripts.py
import os
import sys
import subprocess
import shutil
from pathlib import Path

# Determine the absolute path to the project root
project_root = Path(__file__).resolve().parent.parent

def test_entire_pipeline_sequentially(tmp_path):
    """
    Executes the entire script pipeline sequentially in a single isolated
    temporary directory so data generated by 01 is available to 02, etc.
    """
    # Copy the required folders into the isolated workspace
    for folder in ["config", "tests"]:
        orig = project_root / folder
        if orig.exists():
            shutil.copytree(orig, tmp_path / folder)

    # Explicitly create the data/synthetic structure so utils.py finds it
    data_dir = tmp_path / "data" / "synthetic"
    data_dir.mkdir(parents=True, exist_ok=True)

    # Define the exact order of the pipeline
    pipeline = [
        "icare_risk.scripts.a_generate_data",
        "icare_risk.scripts.b_build_features_icare",
        "icare_risk.scripts.c_evaluate_scores",
        "icare_risk.scripts.d_evaluate_thresholds",
        "icare_risk.scripts.e_validate_scores",
        "icare_risk.scripts.f_find_clinical_codes",
        #"scripts.main"
    ]

    env = os.environ.copy()
    #env["PYTHONPATH"] = str(project_root)

    env["PYTHONPATH"] = str(project_root / "src") + os.pathsep + str(project_root)

    for module in pipeline:
        result = subprocess.run(
            [sys.executable, "-m", module],
            cwd=tmp_path,
            env=env,
            capture_output=True,
            text=True
        )

        error_msg = (
            f"Script {module} failed with exit code {result.returncode}.\n"
            f"--- STDOUT ---\n{result.stdout}\n"
            f"--- STDERR ---\n{result.stderr}\n"
        )
        assert result.returncode == 0, error_msg